version: '3.8'

services:
  foreach-movies-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true

# docker-compose up -d foreach-movies-dev
# docker-compose down foreach-movies-dev 